# Generated by Django 4.2.7 on 2024-02-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='static/video')),
            ],
        ),
        migrations.CreateModel(
            name='Movies_Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ms_type', models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], max_length=10)),
                ('flyer', models.ImageField(upload_to='static/images/assets/flyer')),
                ('age_limit', models.CharField(choices=[('ALL', 'ALL'), ('kids', 'Kids')], max_length=10)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videos')),
            ],
        ),
    ]
